### ISSUE TITLE
Cannot change REC_BATCH_SIZE to other number instead of 1？

### ISSUE THREAD

**Issue by Asher-1** [SthPhoenix/InsightFace-REST#39] opened 2021-06-01 01:41 UTC
ERROR: Failed to parse the ONNX
In node -1 (scaleHelper): UNSUPPORTED_NODE: Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
tensorrt version: 7.2.1.6
onnx version: 1.7.0

**Comment by SthPhoenix** [comment] 2021-06-01 03:32
What recognition model are you using?

**Comment by Asher-1** [comment] 2021-06-01 11:24
arcface_100

**Comment by SthPhoenix** [comment] 2021-06-01 17:31
Is this model downloaded from original insightface repo? I can't reproduce your exception with both original model and preconverted model linked in readme.
Though thanks to your issue I found related bug with newer glintr100 model, which will be patched later.

**Comment by Asher-1** [comment] 2021-06-02 01:07
Thanks for your help.
Rebuilding libnvonnxparser.so.7.2.2 from https://github.com/onnx/onnx-tensorrt.git and replacing nvidia official  tensorrt internal onnxparser library with this shared library works for me! I suppose that it is about official releases, issue with onnx parser.
By the way, 
some errors occur when using  glintr100 model with applying REC_BATCH_SIZE to a custom number greater than 1.
from reshape_onnx.py
 if mode != 'arcface':
                d[2].dim_value = math.ceil(h / divisor)
                d[3].dim_value = math.ceil(w / divisor)

**Comment by SthPhoenix** [comment] 2021-06-02 03:28
> Thanks for your help.
> Rebuilding libnvonnxparser.so.7.2.2 from https://github.com/onnx/onnx-tensorrt.git and replacing nvidia official tensorrt internal onnxparser library with this shared library works for me! I suppose that it is nvidia official issue with onnx parser.

Oh, now I recall that bug, there was even workaround in one of previous versions.

> By the way, some errors occur when using glintr100 model with applying REC_BATCH_SIZE to a custom number greater than 1.
> from reshape_onnx.py
> if mode != 'arcface':
> d[2].dim_value = math.ceil(h / divisor)
> d[3].dim_value = math.ceil(w / divisor)

Yes, I meant this, it's fixed in one of yesterday commits.

**Closed** 2021-06-03 00:33 UTC
