### ISSUE TITLE
No module named 'cupy'

### ISSUE THREAD

**Issue by tonhathuy** [SthPhoenix/InsightFace-REST#61] opened 2021-11-28 12:04 UTC
![image](https://user-images.githubusercontent.com/45118883/143766850-86948451-5dd1-420f-936a-592b719db8a1.png)
I got a bug `No module named 'cupy'` when run deploy_cpu.sh , I try to run `pip install cupy `but it can't install

**Comment by SthPhoenix** [comment] 2021-11-30 19:20
Hi! Cupy isn't required for CPU version. 
FastAPI for some reason throws errors after logging warning message, but should work as intended.

**Comment by SthPhoenix** [comment] 2021-12-29 18:54
Should be fixed with cf64b7e8d9109982974597834548ee821f1f538f

**Closed by SthPhoenix** 2021-12-29 18:54 UTC
