### ISSUE TITLE
Failed to create arcface tensorrt model with tensorrt 20.10

### ISSUE THREAD

**Issue by akashmanna** [SthPhoenix/InsightFace-REST#9] opened 2020-11-03 06:13 UTC
Hi, I was trying to convert Arcface model to TensorRT plan using ```build_insight_trt.py``` and TensorRT 20.10, but it failed with the following error-

```
[TensorRT] ERROR: (Unnamed Layer* 480) [Shuffle]: at most one dimension may be inferred
ERROR: Failed to parse the ONNX file: /models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.tmp
In node -1 (scaleHelper): UNSUPPORTED_NODE: Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
```

Require this because Triton supports custom Python backends only with Triton 20.10 and not 20.09, and the model converted using TensorRT 20.09 is unsupported with Triton 20.10 (Triton 20.10 supports TensorRT 20.10)

Can this be fixed? 

Also, Thanks for the amazing work!

**Comment by SthPhoenix** [comment] 2020-11-03 06:50
Hi! I haven't tested 20.10 yet. I'll check how that can be fixed.

BTW,  I'm also currently working on implementing Triton backend. It's actually ready, but I'm stucked with shared memory, which may improve single thread throughput.
Also looks like with Triton server CPU becomes a bottleneck, since pre- and postprocessing with python takes too much resources and I can't saturate multiple GPUs.

**Comment by SthPhoenix** [comment] 2020-11-03 20:10
@akashmanna, I wasn't able to reproduce your bug, building TRT engine works just fine with 20.10 image. 

Ensure that you have latest 455x GPU drivers. For some reason building RetinaFace engine works fine with 450 drivers, while ArcFace fails. Actually according to TensorRT Docker release notes they both should fail, since 455x drivers are required for non-tesla GPUs

**Comment by akashmanna** [comment] 2020-11-05 16:44
Hi, I tried again, with building Arcface Model on TRT 20.10, but it fails with the same error. 
I am currently having 455x Driver on T4 GPU, and just replacing the version in ```Dockerfile.converter```

Anyway, I'm sticking to 20.09 for the time being and deploying both trt models generated from your repo independently on Triton, and I'm also facing the same- CPU becoming a bottleneck! But I had another query- I've observed the output of TRT model from Triton are raw outputs from the Retinaface model, which is a big numpy array that takes time to transfer over HTTP (from Triton) and I need to perform NMS and other post processing on the client side. Were you able to handle the NMS logic in Triton itself? If you have any suggestions for the same, it'll be really helpful

**Comment by SthPhoenix** [comment] 2020-11-05 22:20
> Hi, I tried again, with building Arcface Model on TRT 20.10, but it fails with the same error.
> I am currently having 455x Driver on T4 GPU, and just replacing the version in `Dockerfile.converter`
> 
> Anyway, I'm sticking to 20.09 for the time being and deploying both trt models generated from your repo independently on Triton, and I'm also facing the same- CPU becoming a bottleneck! But I had another query- I've observed the output of TRT model from Triton are raw outputs from the Retinaface model, which is a big numpy array that takes time to transfer over HTTP (from Triton) and I need to perform NMS and other post processing on the client side. Were you able to handle the NMS logic in Triton itself? If you have any suggestions for the same, it'll be really helpful


That's strange, might be some issues with T4 and drivers.

I am currently running Triton server and client on same machine, and using higher number of client workers to mitigate HTTP latency.  `perf_client` shows that using shared memory can greatly reduce latency and overall processing in single thread, to almost same values when using TensorRT in one container with postprocessing. But I haven't got much time to figure out how to use SHM in Python yet.

Looks like that best way to optimize CPU usage would be, obviously, replacing Python pre- and postprocessing with C++, which also can be easier integrated into Triton server. But it'll take much time for me to implement, since I haven't coded on C/C++ for years now.

**Comment by akashmanna** [comment] 2020-11-07 09:38
Okay. Thanks a lot for your help. I'm closing this issue for now

**Comment by SthPhoenix** [comment] 2020-11-07 20:32
BTW, could you please check latest api_trt version with fp16 support? Tesla T4 seems to have huge advantage in performance when using fp16.

**Comment by akashmanna** [comment] 2020-11-14 07:01
@SthPhoenix  The model gets successfully converted when I pass ```max_batch_size=1``` in  ```build_insight_trt.py```, but I get the same error when I increase the max_batch_size to any other value. Any idea!?

Also, I had been a bit busy with some other work lately, I'll checkout the performance with FP16 on T4!

**Comment by akashmanna** [comment] 2020-11-14 07:19
Some basic debugging got me to here, the error comes at this line: 

https://github.com/SthPhoenix/InsightFace-REST/blob/4b284c6d0f4c4b1ba5d39fa31243c81f1aa20f77/src/converters/modules/converters/onnx_to_trt.py#L46

The exact error is 
```
[TensorRT] ERROR: (Unnamed Layer* 480) [Shuffle]: at most one dimension may be inferred
ERROR: Failed to parse the ONNX file: /models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.tmp
In node -1 (scaleHelper): UNSUPPORTED_NODE: Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
``` 

But since the conversion successfully happens for max_batch_size=1, I believe there is some issue in the creation of the optimization profile here https://github.com/SthPhoenix/InsightFace-REST/blob/4b284c6d0f4c4b1ba5d39fa31243c81f1aa20f77/src/converters/modules/converters/onnx_to_trt.py#L38

**Comment by akashmanna** [comment] 2020-11-14 08:19
An update: I ran with verbose outputs, apparently the error is in conversion of BatchNorm layer.
```
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_beta
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_moving_mean
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_moving_var
[TensorRT] VERBOSE: ModelImporter.cpp:125: fc1 [BatchNormalization] inputs: [pre_fc1 -> (-1, -1)], [fc1_gamma -> (512)], [fc1_beta -> (512)], [fc1_moving_mean -> (512)], [fc1_moving_var -> (512)], 
[TensorRT] ERROR: (Unnamed Layer* 480) [Shuffle]: at most one dimension may be inferred
ERROR: Failed to parse the ONNX file: /models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.tmp
In node -1 (scaleHelper): UNSUPPORTED_NODE: Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
```

Apparently Batchnorm was supporting only 4 or 5 dimension inputs. I found a similar issue the repo of _onnx_tensorrt_ here https://github.com/onnx/onnx-tensorrt/issues/566
And a very recent fix for it with this PR https://github.com/onnx/onnx-tensorrt/pull/569

I'll try building it from source to check if it works

**Comment by SthPhoenix** [comment] 2020-11-14 08:31
I've seen similar error when building Centerface model with batch size > 1. 
Actually for some reason TensorRT `build_engine` fails for some models even without optimization profile, while `build_cuda_engine` works as expected, but it can't be used to create engine with dynamic shapes.

In current version of converter I use `build_cuda_engine` for batch size = 1,  so that might be the reason why you can build engine now.

Try using `trtexec` to create engine with different batch sizes as workaround.

**Comment by SthPhoenix** [comment] 2020-11-15 21:45
I have tested conversion with batch size>1. Yes, it seems to be broken for TRT 7.2 for now.
Workaround with `trtexec` seems to be working:

```
trtexec --onnx=/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx --minShapes=data:1x3x640x640 --optShapes=data:10x3x640x640 --maxShapes=data:10x3x640x640 --saveEngine=/models/trt-engines/arcface_r100_v1/arcface_r100_v1_batched.plan
```

**Comment by akashmanna** [comment] 2020-11-17 09:06
Thanks!  This worked perfectly!
Can I use trtexec similarly to convert the retinaface model as well to use batching the same way?

**Comment by SthPhoenix** [comment] 2020-11-17 16:14
> Can I use trtexec similarly to convert the retinaface model as well to use batching the same way?

Haven't tested it, but it should work.

**Comment by shroudie** [comment] 2020-11-28 06:15
> I have tested conversion with batch size>1. Yes, it seems to be broken for TRT 7.2 for now.
> Workaround with `trtexec` seems to be working:
> 
> ```
> trtexec --onnx=/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx --explicitBatch --minShapes=data:1x3x112x112 --optShapes=data:10x3x112x112 --maxShapes=data:10x3x112x112 --saveEngine=/models/trt-engines/arcface_r100_v1/arcface_r100_v1_batched.plan
> ```

This does not happen to be the case for me, are you sure you exported the onnx model with dynamic inputs and outputs? Would you mind share your onnx model? Thanks a lot

**Comment by SthPhoenix** [comment] 2020-11-28 07:56
> > I have tested conversion with batch size>1. Yes, it seems to be broken for TRT 7.2 for now.
> > Workaround with `trtexec` seems to be working:
> > ```
> > trtexec --onnx=/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx --explicitBatch --minShapes=data:1x3x112x112 --optShapes=data:10x3x112x112 --maxShapes=data:10x3x112x112 --saveEngine=/models/trt-engines/arcface_r100_v1/arcface_r100_v1_batched.plan
> > ```
> 
> This does not happen to be the case for me, are you sure you exported the onnx model with dynamic inputs and outputs? Would you mind share your onnx model? Thanks a lot

**Comment by shroudie** [comment] 2020-11-30 05:59
> > > I have tested conversion with batch size>1. Yes, it seems to be broken for TRT 7.2 for now.
> > > Workaround with `trtexec` seems to be working:
> > > ```
> > > trtexec --onnx=/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx --explicitBatch --minShapes=data:1x3x112x112 --optShapes=data:10x3x112x112 --maxShapes=data:10x3x112x112 --saveEngine=/models/trt-engines/arcface_r100_v1/arcface_r100_v1_batched.plan
> > > ```
> > 
> > 
> > This does not happen to be the case for me, are you sure you exported the onnx model with dynamic inputs and outputs? Would you mind share your onnx model? Thanks a lot
> 
> You need to reshape onnx model before conversion.
> You can use `reshape_onnx_input` from [reshape_onnx.py](https://github.com/SthPhoenix/InsightFace-REST/blob/master/src/converters/modules/converters/reshape_onnx.py) like this:
> 
> ```
> reshape_onnx_input("/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx", "/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.temp", im_size=[112,112], batch_size=-1)
> ```
> 
> And than use trtexec to build engine:
> 
> ```
> trtexec --onnx=/models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.temp --explicitBatch --minShapes=data:1x3x112x112 --optShapes=data:16x3x112x112 --maxShapes=data:16x3x112x112 --saveEngine=/models/trt-engines/arcface_r100_v1/arcface_r100_v1_batched.plan
> ```

Thanks a lot Phoenix, I will try it at some point!

**Comment by SthPhoenix** [comment] 2020-11-30 17:28
Well... I have finally managed to actually check this solution, it's not working.
Reshaped model produces same error with trtexec as with Python TRT API.
Non-reshaped model converts, but I haven't checked it, @akashmanna have you checked outputs of converted model?

**Comment by akashmanna** [comment] 2020-12-02 05:44
I haven't checked the outputs and their accuracy, but I changed the `batch_size=1` to some other >1 value here:
https://github.com/SthPhoenix/InsightFace-REST/blob/942582dcd212af60686ef43cb90936c71ce9ce68/src/converters/build_insight_trt.py#L51 

and let it fail in the tensorrt conversion step.

The ONNX conversion is successful but it fails in onnx to tensorrt conversion like here - https://github.com/SthPhoenix/InsightFace-REST/issues/9#issuecomment-727159371

But using the onnx.temp file hence generated, I used `trtexec` to generate the tensorrt plan file, which I tested was yielding outputs of correct shape for batchsize >1

**Comment by SthPhoenix** [comment] 2020-12-02 06:04
> I haven't checked the outputs and their accuracy, but I changed the `batch_size=1` to some other >1 value here:
> https://github.com/SthPhoenix/InsightFace-REST/blob/942582dcd212af60686ef43cb90936c71ce9ce68/src/converters/build_insight_trt.py#L51
> 
> and let it fail in the tensorrt conversion step.
> 
> The ONNX conversion is successful but it fails in onnx to tensorrt conversion like here - [#9 (comment)](https://github.com/SthPhoenix/InsightFace-REST/issues/9#issuecomment-727159371)
> 
> But using the onnx.temp file hence generated, I used `trtexec` to generate the tensorrt plan file, which I tested was yielding outputs of correct shape for batchsize >1.
> 
> By correct shape I mean if I passed a vector of shape (2, 3, 112, 112), I was getting output of shape (2, 512)

Hm, that's weird, I'm getting conversion error for same scenario with 20.10 and 20.11 TRT image.

**Comment by shroudie** [comment] 2020-12-02 09:03
> I haven't checked the outputs and their accuracy, but I changed the `batch_size=1` to some other >1 value here:
> https://github.com/SthPhoenix/InsightFace-REST/blob/942582dcd212af60686ef43cb90936c71ce9ce68/src/converters/build_insight_trt.py#L51
> 
> and let it fail in the tensorrt conversion step.
> 
> The ONNX conversion is successful but it fails in onnx to tensorrt conversion like here - [#9 (comment)](https://github.com/SthPhoenix/InsightFace-REST/issues/9#issuecomment-727159371)
> 
> But using the onnx.temp file hence generated, I used `trtexec` to generate the tensorrt plan file, which I tested was yielding outputs of correct shape for batchsize >1.
> 
> By correct shape I mean if I passed a vector of shape (2, 3, 112, 112), I was getting output of shape (2, 512)

Is it possible to share your model? Or which arcface model you were experimenting with? Thanks

**Comment by shroudie** [comment] 2020-12-02 22:19
> I haven't checked the outputs and their accuracy, but I changed the `batch_size=1` to some other >1 value here:
> https://github.com/SthPhoenix/InsightFace-REST/blob/942582dcd212af60686ef43cb90936c71ce9ce68/src/converters/build_insight_trt.py#L51
> 
> and let it fail in the tensorrt conversion step.
> 
> The ONNX conversion is successful but it fails in onnx to tensorrt conversion like here - [#9 (comment)](https://github.com/SthPhoenix/InsightFace-REST/issues/9#issuecomment-727159371)
> 
> But using the onnx.temp file hence generated, I used `trtexec` to generate the tensorrt plan file, which I tested was yielding outputs of correct shape for batchsize >1.
> 
> By correct shape I mean if I passed a vector of shape (2, 3, 112, 112), I was getting output of shape (2, 512)

Would you mind share your model? Or which trtexec version you were experimenting with? Thanks

**Comment by SthPhoenix** [comment] 2020-12-06 16:11
> An update: I ran with verbose outputs, apparently the error is in conversion of BatchNorm layer.
> 
> ```
> [TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_beta
> [TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_moving_mean
> [TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: fc1_moving_var
> [TensorRT] VERBOSE: ModelImporter.cpp:125: fc1 [BatchNormalization] inputs: [pre_fc1 -> (-1, -1)], [fc1_gamma -> (512)], [fc1_beta -> (512)], [fc1_moving_mean -> (512)], [fc1_moving_var -> (512)], 
> [TensorRT] ERROR: (Unnamed Layer* 480) [Shuffle]: at most one dimension may be inferred
> ERROR: Failed to parse the ONNX file: /models/onnx/arcface_r100_v1/arcface_r100_v1.onnx.tmp
> In node -1 (scaleHelper): UNSUPPORTED_NODE: Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
> ```
> 
> Apparently Batchnorm was supporting only 4 or 5 dimension inputs. I found a similar issue the repo of _onnx_tensorrt_ here [onnx/onnx-tensorrt#566](https://github.com/onnx/onnx-tensorrt/issues/566)
> And a very recent fix for it with this PR [onnx/onnx-tensorrt#569](https://github.com/onnx/onnx-tensorrt/pull/569)
> 
> I'll try building it from source to check if it works

Looks like TensorRT ONNX parser is linked to latest release of [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt/tree/7.2.1). 
Fix for this issue is already in master branch of onnx-tensorrt, but it wasn't released yet, so the issue should be fixed in TensorRT release next to onnx-tensorrt release...
Or you can try building onnx-tensorrt from source and use it's built-in onnx2trt util to build engine.

**Comment by SthPhoenix** [comment] 2020-12-21 10:55
Working workaround for 20.10-20.12 images:

Run `/opt/tensorrt/install_opensource.sh -b master` inside active TensorRT container. 

For some reason this command won't update OSS utilities if run during build process.

**Comment by SthPhoenix** [comment] 2020-12-26 20:34
I have added workaround for 20.12 image in following commit: faae6939bc4b2df70e47108036f110b50359522b
It should work for a while, but must be updated later, when https://github.com/onnx/onnx-tensorrt/pull/569 will be included in `onnx-tensorrt`release and merged into TensorRT release.

**Closed by SthPhoenix** 2020-12-26 20:34 UTC
